[tools]
lune = "filiptibell/lune@0.9.4"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
rojo = "quenty/rojo@7.4.3-quenty-npm-canary.2"
selene = "Kampfkarren/selene@0.28.0"
