[tools]
lune = "filiptibell/lune@0.9.4"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
rojo = "quenty/rojo@7.4.3-quenty-npm-canary.2"
selene = "Kampfkarren/selene@0.28.0"
luau-lsp = "johnnymorganz/luau-lsp@1.51.0"
blink = "1Axen/blink@0.17.4"