[package]
name = "mediamonks/default"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Comm = "sleitnick/comm@1.0.1"
Knit = "sleitnick/knit@^1.4"
Signal = "sleitnick/signal@2.0.1"
Component = "sleitnick/component@2.4.6"
Janitor = "howmanysmall/janitor@^1"
TableUtil = "sleitnick/table-util@1.2.1"
Fusion = "elttob/fusion@0.3.0"
Cmdr = "evaera/cmdr@1.12.0"
