[package]
name = "mediamonks/default"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Component = "sleitnick/component@2.4.6"
Janitor = "howmanysmall/janitor@^1"
TableUtil = "sleitnick/table-util@1.2.1"
Cmdr = "evaera/cmdr@1.12.0"
